/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Currency info
 *
 * @param code The ISO-4217 currency code
 * @param countryCodes A list of ISO-3166 country codes of countries supporting this currency
 * @param symbol The currency symbol
 */
@Serializable

data class Currency (

    /* The ISO-4217 currency code */
    @SerialName(value = "code") val code: kotlin.String? = null,

    /* A list of ISO-3166 country codes of countries supporting this currency */
    @SerialName(value = "countryCodes") val countryCodes: kotlin.collections.List<kotlin.String>? = null,

    /* The currency symbol */
    @SerialName(value = "symbol") val symbol: kotlin.String? = null

) {


}

