/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Error

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An ISO-6801 date-time response
 *
 * @param errors 
 * @param `data` The date-time in ISO-6801 format: yyyyMMdd'T'HHmmssZ
 */
@Serializable

data class DateTimeResponse (

    @SerialName(value = "errors") val errors: kotlin.collections.List<Error>? = null,

    /* The date-time in ISO-6801 format: yyyyMMdd'T'HHmmssZ */
    @SerialName(value = "data") val `data`: kotlinx.datetime.Instant? = null

) {


}

