/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Error

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A decimal distance (in miles or kilometers)
 *
 * @param errors 
 * @param `data` The distance in units as set by the distanceUnit param (defaults to miles)
 */
@Serializable

data class DistanceResponse (

    @SerialName(value = "errors") val errors: kotlin.collections.List<Error>? = null,

    /* The distance in units as set by the distanceUnit param (defaults to miles) */
    @SerialName(value = "data") val `data`: kotlin.Double? = null

) {


}

