/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.ErrorCode

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An error that occurred processing the request
 *
 * @param code 
 * @param message 
 */
@Serializable

data class Error (

    @SerialName(value = "code") val code: ErrorCode? = null,

    @SerialName(value = "message") val message: kotlin.String? = null

) {


}

