/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A language supported by the service
 *
 * @param code 
 * @param name 
 */
@Serializable

data class LanguageDescriptor (

    @SerialName(value = "code") val code: LanguageDescriptor.Code? = null,

    @SerialName(value = "name") val name: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: undefined,aa,ab,ae,af,ak,am,an,ar,`as`,av,ay,az,ba,be,bg,bh,bi,bm,bn,bo,br,bs,ca,ce,ch,co,cr,cs,cu,cv,cy,da,de,dv,dz,ee,el,en,eo,es,et,eu,fa,ff,fi,fj,fo,fr,fy,ga,gd,gl,gn,gu,gv,ha,he,hi,ho,hr,ht,hu,hy,hz,ia,id,ie,ig,ii,ik,io,`is`,`it`,iu,ja,jv,ka,kg,ki,kj,kk,kl,km,kn,ko,kr,ks,ku,kv,kw,ky,la,lb,lg,li,ln,lo,lt,lu,lv,mg,mh,mi,mk,ml,mn,mr,ms,mt,my,na,nb,nd,ne,ng,nl,nn,no,nr,nv,ny,oc,oj,om,or,os,pa,pi,pl,ps,pt,qu,rm,rn,ro,ru,rw,sa,sc,sd,se,sg,si,sk,sl,sm,sn,so,sq,sr,ss,st,su,sv,sw,ta,te,tg,th,ti,tk,tl,tn,to,tr,ts,tt,tw,ty,ug,uk,ur,uz,ve,vi,vo,wa,wo,xh,yi,yo,za,zh,zu
     */
    @Serializable
    enum class Code(val value: kotlin.String) {
        @SerialName(value = "undefined") undefined("undefined"),
        @SerialName(value = "aa") aa("aa"),
        @SerialName(value = "ab") ab("ab"),
        @SerialName(value = "ae") ae("ae"),
        @SerialName(value = "af") af("af"),
        @SerialName(value = "ak") ak("ak"),
        @SerialName(value = "am") am("am"),
        @SerialName(value = "an") an("an"),
        @SerialName(value = "ar") ar("ar"),
        @SerialName(value = "as") `as`("as"),
        @SerialName(value = "av") av("av"),
        @SerialName(value = "ay") ay("ay"),
        @SerialName(value = "az") az("az"),
        @SerialName(value = "ba") ba("ba"),
        @SerialName(value = "be") be("be"),
        @SerialName(value = "bg") bg("bg"),
        @SerialName(value = "bh") bh("bh"),
        @SerialName(value = "bi") bi("bi"),
        @SerialName(value = "bm") bm("bm"),
        @SerialName(value = "bn") bn("bn"),
        @SerialName(value = "bo") bo("bo"),
        @SerialName(value = "br") br("br"),
        @SerialName(value = "bs") bs("bs"),
        @SerialName(value = "ca") ca("ca"),
        @SerialName(value = "ce") ce("ce"),
        @SerialName(value = "ch") ch("ch"),
        @SerialName(value = "co") co("co"),
        @SerialName(value = "cr") cr("cr"),
        @SerialName(value = "cs") cs("cs"),
        @SerialName(value = "cu") cu("cu"),
        @SerialName(value = "cv") cv("cv"),
        @SerialName(value = "cy") cy("cy"),
        @SerialName(value = "da") da("da"),
        @SerialName(value = "de") de("de"),
        @SerialName(value = "dv") dv("dv"),
        @SerialName(value = "dz") dz("dz"),
        @SerialName(value = "ee") ee("ee"),
        @SerialName(value = "el") el("el"),
        @SerialName(value = "en") en("en"),
        @SerialName(value = "eo") eo("eo"),
        @SerialName(value = "es") es("es"),
        @SerialName(value = "et") et("et"),
        @SerialName(value = "eu") eu("eu"),
        @SerialName(value = "fa") fa("fa"),
        @SerialName(value = "ff") ff("ff"),
        @SerialName(value = "fi") fi("fi"),
        @SerialName(value = "fj") fj("fj"),
        @SerialName(value = "fo") fo("fo"),
        @SerialName(value = "fr") fr("fr"),
        @SerialName(value = "fy") fy("fy"),
        @SerialName(value = "ga") ga("ga"),
        @SerialName(value = "gd") gd("gd"),
        @SerialName(value = "gl") gl("gl"),
        @SerialName(value = "gn") gn("gn"),
        @SerialName(value = "gu") gu("gu"),
        @SerialName(value = "gv") gv("gv"),
        @SerialName(value = "ha") ha("ha"),
        @SerialName(value = "he") he("he"),
        @SerialName(value = "hi") hi("hi"),
        @SerialName(value = "ho") ho("ho"),
        @SerialName(value = "hr") hr("hr"),
        @SerialName(value = "ht") ht("ht"),
        @SerialName(value = "hu") hu("hu"),
        @SerialName(value = "hy") hy("hy"),
        @SerialName(value = "hz") hz("hz"),
        @SerialName(value = "ia") ia("ia"),
        @SerialName(value = "id") id("id"),
        @SerialName(value = "ie") ie("ie"),
        @SerialName(value = "ig") ig("ig"),
        @SerialName(value = "ii") ii("ii"),
        @SerialName(value = "ik") ik("ik"),
        @SerialName(value = "io") io("io"),
        @SerialName(value = "is") `is`("is"),
        @SerialName(value = "it") `it`("it"),
        @SerialName(value = "iu") iu("iu"),
        @SerialName(value = "ja") ja("ja"),
        @SerialName(value = "jv") jv("jv"),
        @SerialName(value = "ka") ka("ka"),
        @SerialName(value = "kg") kg("kg"),
        @SerialName(value = "ki") ki("ki"),
        @SerialName(value = "kj") kj("kj"),
        @SerialName(value = "kk") kk("kk"),
        @SerialName(value = "kl") kl("kl"),
        @SerialName(value = "km") km("km"),
        @SerialName(value = "kn") kn("kn"),
        @SerialName(value = "ko") ko("ko"),
        @SerialName(value = "kr") kr("kr"),
        @SerialName(value = "ks") ks("ks"),
        @SerialName(value = "ku") ku("ku"),
        @SerialName(value = "kv") kv("kv"),
        @SerialName(value = "kw") kw("kw"),
        @SerialName(value = "ky") ky("ky"),
        @SerialName(value = "la") la("la"),
        @SerialName(value = "lb") lb("lb"),
        @SerialName(value = "lg") lg("lg"),
        @SerialName(value = "li") li("li"),
        @SerialName(value = "ln") ln("ln"),
        @SerialName(value = "lo") lo("lo"),
        @SerialName(value = "lt") lt("lt"),
        @SerialName(value = "lu") lu("lu"),
        @SerialName(value = "lv") lv("lv"),
        @SerialName(value = "mg") mg("mg"),
        @SerialName(value = "mh") mh("mh"),
        @SerialName(value = "mi") mi("mi"),
        @SerialName(value = "mk") mk("mk"),
        @SerialName(value = "ml") ml("ml"),
        @SerialName(value = "mn") mn("mn"),
        @SerialName(value = "mr") mr("mr"),
        @SerialName(value = "ms") ms("ms"),
        @SerialName(value = "mt") mt("mt"),
        @SerialName(value = "my") my("my"),
        @SerialName(value = "na") na("na"),
        @SerialName(value = "nb") nb("nb"),
        @SerialName(value = "nd") nd("nd"),
        @SerialName(value = "ne") ne("ne"),
        @SerialName(value = "ng") ng("ng"),
        @SerialName(value = "nl") nl("nl"),
        @SerialName(value = "nn") nn("nn"),
        @SerialName(value = "no") no("no"),
        @SerialName(value = "nr") nr("nr"),
        @SerialName(value = "nv") nv("nv"),
        @SerialName(value = "ny") ny("ny"),
        @SerialName(value = "oc") oc("oc"),
        @SerialName(value = "oj") oj("oj"),
        @SerialName(value = "om") om("om"),
        @SerialName(value = "or") or("or"),
        @SerialName(value = "os") os("os"),
        @SerialName(value = "pa") pa("pa"),
        @SerialName(value = "pi") pi("pi"),
        @SerialName(value = "pl") pl("pl"),
        @SerialName(value = "ps") ps("ps"),
        @SerialName(value = "pt") pt("pt"),
        @SerialName(value = "qu") qu("qu"),
        @SerialName(value = "rm") rm("rm"),
        @SerialName(value = "rn") rn("rn"),
        @SerialName(value = "ro") ro("ro"),
        @SerialName(value = "ru") ru("ru"),
        @SerialName(value = "rw") rw("rw"),
        @SerialName(value = "sa") sa("sa"),
        @SerialName(value = "sc") sc("sc"),
        @SerialName(value = "sd") sd("sd"),
        @SerialName(value = "se") se("se"),
        @SerialName(value = "sg") sg("sg"),
        @SerialName(value = "si") si("si"),
        @SerialName(value = "sk") sk("sk"),
        @SerialName(value = "sl") sl("sl"),
        @SerialName(value = "sm") sm("sm"),
        @SerialName(value = "sn") sn("sn"),
        @SerialName(value = "so") so("so"),
        @SerialName(value = "sq") sq("sq"),
        @SerialName(value = "sr") sr("sr"),
        @SerialName(value = "ss") ss("ss"),
        @SerialName(value = "st") st("st"),
        @SerialName(value = "su") su("su"),
        @SerialName(value = "sv") sv("sv"),
        @SerialName(value = "sw") sw("sw"),
        @SerialName(value = "ta") ta("ta"),
        @SerialName(value = "te") te("te"),
        @SerialName(value = "tg") tg("tg"),
        @SerialName(value = "th") th("th"),
        @SerialName(value = "ti") ti("ti"),
        @SerialName(value = "tk") tk("tk"),
        @SerialName(value = "tl") tl("tl"),
        @SerialName(value = "tn") tn("tn"),
        @SerialName(value = "to") to("to"),
        @SerialName(value = "tr") tr("tr"),
        @SerialName(value = "ts") ts("ts"),
        @SerialName(value = "tt") tt("tt"),
        @SerialName(value = "tw") tw("tw"),
        @SerialName(value = "ty") ty("ty"),
        @SerialName(value = "ug") ug("ug"),
        @SerialName(value = "uk") uk("uk"),
        @SerialName(value = "ur") ur("ur"),
        @SerialName(value = "uz") uz("uz"),
        @SerialName(value = "ve") ve("ve"),
        @SerialName(value = "vi") vi("vi"),
        @SerialName(value = "vo") vo("vo"),
        @SerialName(value = "wa") wa("wa"),
        @SerialName(value = "wo") wo("wo"),
        @SerialName(value = "xh") xh("xh"),
        @SerialName(value = "yi") yi("yi"),
        @SerialName(value = "yo") yo("yo"),
        @SerialName(value = "za") za("za"),
        @SerialName(value = "zh") zh("zh"),
        @SerialName(value = "zu") zu("zu");
    }

}

