/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Result metadata (currently only associated with collection results)
 *
 * @param currentOffset The zero-ary offset into the results (0 is the first result)
 * @param totalCount The total number of results across pages
 */
@Serializable

data class Metadata (

    /* The zero-ary offset into the results (0 is the first result) */
    @SerialName(value = "currentOffset") val currentOffset: kotlin.Long? = null,

    /* The total number of results across pages */
    @SerialName(value = "totalCount") val totalCount: kotlin.Long? = null

) {


}

