/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*

/**
 * One of a set of enumerated populated-place types known by the service (currently only level-2 admin divisions and cities) 
 *
 * Values: ADM2,CITY,ISLAND
 */
@Serializable
enum class PopulatedPlaceType(val value: kotlin.String) {

    @SerialName(value = "ADM2")
    ADM2("ADM2"),

    @SerialName(value = "CITY")
    CITY("CITY"),

    @SerialName(value = "ISLAND")
    ISLAND("ISLAND");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is PopulatedPlaceType) "$data" else null

        /**
         * Returns a valid [PopulatedPlaceType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): PopulatedPlaceType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

