/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Error
import org.openapitools.client.models.PopulatedPlaceDetails

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Populated-place details response
 *
 * @param errors 
 * @param `data` 
 */
@Serializable

data class PopulatedPlaceResponse (

    @SerialName(value = "errors") val errors: kotlin.collections.List<Error>? = null,

    @SerialName(value = "data") val `data`: PopulatedPlaceDetails? = null

) {


}

