/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Minimal country region info
 *
 * @param countryCode An ISO-3166 country code
 * @param fipsCode The FIPS 10-4 region code
 * @param isoCode The ISO region code
 * @param name The region name (varies by languageCode)
 * @param wikiDataId The region WikiData id
 */
@Serializable

data class RegionSummary (

    /* An ISO-3166 country code */
    @SerialName(value = "countryCode") val countryCode: kotlin.String? = null,

    /* The FIPS 10-4 region code */
    @SerialName(value = "fipsCode") val fipsCode: kotlin.String? = null,

    /* The ISO region code */
    @SerialName(value = "isoCode") val isoCode: kotlin.String? = null,

    /* The region name (varies by languageCode) */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The region WikiData id */
    @SerialName(value = "wikiDataId") val wikiDataId: kotlin.String? = null

) {


}

