/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Error

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An ISO-8601 time response
 *
 * @param errors 
 * @param `data` The time in ISO-8601 format: HHmmss.SSSZ
 */
@Serializable

data class TimeResponse (

    @SerialName(value = "errors") val errors: kotlin.collections.List<Error>? = null,

    /* The time in ISO-8601 format: HHmmss.SSSZ */
    @SerialName(value = "data") val `data`: kotlin.String? = null

) {


}

