/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.Error

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A time-zone
 *
 * @param errors 
 * @param id The time-zone id
 * @param name The time-zone name
 * @param rawUtcOffsetHours The number of hours this time-zone is offset from UTC
 */
@Serializable

data class TimeZoneResponse (

    @SerialName(value = "errors") val errors: kotlin.collections.List<Error>? = null,

    /* The time-zone id */
    @SerialName(value = "id") val id: kotlin.String? = null,

    /* The time-zone name */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* The number of hours this time-zone is offset from UTC */
    @SerialName(value = "rawUtcOffsetHours") val rawUtcOffsetHours: kotlin.Int? = null

) {


}

