//
// BaseCollectionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Common properties for all collection  responses */
public struct BaseCollectionResponse: Codable, JSONEncodable, Hashable {

    public var errors: [ModelError]?
    public var links: [Link]?
    public var metadata: Metadata?

    public init(errors: [ModelError]? = nil, links: [Link]? = nil, metadata: Metadata? = nil) {
        self.errors = errors
        self.links = links
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
        case links
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}

