//
// DateTimeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An ISO-6801 date-time response */
public struct DateTimeResponse: Codable, JSONEncodable, Hashable {

    public var errors: [ModelError]?
    /** The date-time in ISO-6801 format: yyyyMMdd'T'HHmmssZ */
    public var data: Date?

    public init(errors: [ModelError]? = nil, data: Date? = nil) {
        self.errors = errors
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

