//
// DistanceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A decimal distance (in miles or kilometers) */
public struct DistanceResponse: Codable, JSONEncodable, Hashable {

    public var errors: [ModelError]?
    /** The distance in units as set by the distanceUnit param (defaults to miles) */
    public var data: Double?

    public init(errors: [ModelError]? = nil, data: Double? = nil) {
        self.errors = errors
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

