//
// ErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One of a set of enumerated error codes representing the types of errors that can occur processing a request  */
public enum ErrorCode: String, Codable, CaseIterable {
    case accessDenied = "ACCESS_DENIED"
    case entityNotFound = "ENTITY_NOT_FOUND"
    case incompatible = "INCOMPATIBLE"
    case paramInvalid = "PARAM_INVALID"
    case paramsMutuallyExclusive = "PARAMS_MUTUALLY_EXCLUSIVE"
    case requestUnprocessable = "REQUEST_UNPROCESSABLE"
}
