//
// LanguagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A list of languages supported by the system */
public struct LanguagesResponse: Codable, JSONEncodable, Hashable {

    public var errors: [ModelError]?
    public var links: [Link]?
    public var metadata: Metadata?
    public var data: [LanguageDescriptor]?

    public init(errors: [ModelError]? = nil, links: [Link]? = nil, metadata: Metadata? = nil, data: [LanguageDescriptor]? = nil) {
        self.errors = errors
        self.links = links
        self.metadata = metadata
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
        case links
        case metadata
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(links, forKey: .links)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

