//
// Link.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A HATEAOS link */
public struct Link: Codable, JSONEncodable, Hashable {

    public var href: String?
    public var rel: String?

    public init(href: String? = nil, rel: String? = nil) {
        self.href = href
        self.rel = rel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case href
        case rel
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(href, forKey: .href)
        try container.encodeIfPresent(rel, forKey: .rel)
    }
}

