//
// PopulatedPlaceType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One of a set of enumerated populated-place types known by the service (currently only level-2 admin divisions and cities)  */
public enum PopulatedPlaceType: String, Codable, CaseIterable {
    case adm2 = "ADM2"
    case city = "CITY"
    case island = "ISLAND"
}
