//
// RegionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Country region details response */
public struct RegionResponse: Codable, JSONEncodable, Hashable {

    public var errors: [ModelError]?
    public var data: RegionDetails?

    public init(errors: [ModelError]? = nil, data: RegionDetails? = nil) {
        self.errors = errors
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

