//
// TimeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An ISO-8601 time response */
public struct TimeResponse: Codable, JSONEncodable, Hashable {

    public var errors: [ModelError]?
    /** The time in ISO-8601 format: HHmmss.SSSZ */
    public var data: String?

    public init(errors: [ModelError]? = nil, data: String? = nil) {
        self.errors = errors
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errors
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errors, forKey: .errors)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

