//
// TimeZoneDescriptor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A time-zone */
public struct TimeZoneDescriptor: Codable, JSONEncodable, Hashable {

    /** The time-zone id */
    public var id: String?
    /** The time-zone name */
    public var name: String?
    /** The number of hours this time-zone is offset from UTC */
    public var rawUtcOffsetHours: Int?

    public init(id: String? = nil, name: String? = nil, rawUtcOffsetHours: Int? = nil) {
        self.id = id
        self.name = name
        self.rawUtcOffsetHours = rawUtcOffsetHours
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case rawUtcOffsetHours
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(rawUtcOffsetHours, forKey: .rawUtcOffsetHours)
    }
}

