/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.CountryDetails

class CountryDetailsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CountryDetails
        //val modelInstance = CountryDetails()

        // to test the property `code` - The ISO-3166 country code
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `callingCode` - The country dialing prefix
        should("test callingCode") {
            // uncomment below to test the property
            //modelInstance.callingCode shouldBe ("TODO")
        }

        // to test the property `currencyCodes` - A list of supported ISO-4217 currency codes
        should("test currencyCodes") {
            // uncomment below to test the property
            //modelInstance.currencyCodes shouldBe ("TODO")
        }

        // to test the property `flagImageUri` - The country flag image
        should("test flagImageUri") {
            // uncomment below to test the property
            //modelInstance.flagImageUri shouldBe ("TODO")
        }

        // to test the property `name` - The country name (varies by languageCode)
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `numRegions` - The number of regions in this country
        should("test numRegions") {
            // uncomment below to test the property
            //modelInstance.numRegions shouldBe ("TODO")
        }

        // to test the property `wikiDataId` - The country WikiData id
        should("test wikiDataId") {
            // uncomment below to test the property
            //modelInstance.wikiDataId shouldBe ("TODO")
        }

    }
}
