/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Currency

class CurrencyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Currency
        //val modelInstance = Currency()

        // to test the property `code` - The ISO-4217 currency code
        should("test code") {
            // uncomment below to test the property
            //modelInstance.code shouldBe ("TODO")
        }

        // to test the property `countryCodes` - A list of ISO-3166 country codes of countries supporting this currency
        should("test countryCodes") {
            // uncomment below to test the property
            //modelInstance.countryCodes shouldBe ("TODO")
        }

        // to test the property `symbol` - The currency symbol
        should("test symbol") {
            // uncomment below to test the property
            //modelInstance.symbol shouldBe ("TODO")
        }

    }
}
