/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.DateTimeResponse
import org.openapitools.client.models.Error

class DateTimeResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DateTimeResponse
        //val modelInstance = DateTimeResponse()

        // to test the property `errors`
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

        // to test the property ``data`` - The date-time in ISO-6801 format: yyyyMMdd'T'HHmmssZ
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

    }
}
