/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.Metadata

class MetadataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Metadata
        //val modelInstance = Metadata()

        // to test the property `currentOffset` - The zero-ary offset into the results (0 is the first result)
        should("test currentOffset") {
            // uncomment below to test the property
            //modelInstance.currentOffset shouldBe ("TODO")
        }

        // to test the property `totalCount` - The total number of results across pages
        should("test totalCount") {
            // uncomment below to test the property
            //modelInstance.totalCount shouldBe ("TODO")
        }

    }
}
