/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.RegionSummary

class RegionSummaryTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RegionSummary
        //val modelInstance = RegionSummary()

        // to test the property `countryCode` - An ISO-3166 country code
        should("test countryCode") {
            // uncomment below to test the property
            //modelInstance.countryCode shouldBe ("TODO")
        }

        // to test the property `fipsCode` - The FIPS 10-4 region code
        should("test fipsCode") {
            // uncomment below to test the property
            //modelInstance.fipsCode shouldBe ("TODO")
        }

        // to test the property `isoCode` - The ISO region code
        should("test isoCode") {
            // uncomment below to test the property
            //modelInstance.isoCode shouldBe ("TODO")
        }

        // to test the property `name` - The region name (varies by languageCode)
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `wikiDataId` - The region WikiData id
        should("test wikiDataId") {
            // uncomment below to test the property
            //modelInstance.wikiDataId shouldBe ("TODO")
        }

    }
}
