/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import org.openapitools.client.models.TimeZoneResponse
import org.openapitools.client.models.Error

class TimeZoneResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TimeZoneResponse
        //val modelInstance = TimeZoneResponse()

        // to test the property `errors`
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

        // to test the property `id` - The time-zone id
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - The time-zone name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `rawUtcOffsetHours` - The number of hours this time-zone is offset from UTC
        should("test rawUtcOffsetHours") {
            // uncomment below to test the property
            //modelInstance.rawUtcOffsetHours shouldBe ("TODO")
        }

    }
}
